<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Comment' => 'Добавить комментарий',
  'Communication Plan Date' => 'Дата',
  'Create New Task' => 'Создать новое задание',
  'Create Ttsk Task' => '',
  'Person' => 'Менеджер',
  'Task details' => 'Детали задач',
  'Task details: ' => 'Детали задач',
  'Tasks list' => 'Список задач',
  'Tcmn' => '',
  'Tcmn Client Pprs' => 'представитель',
  'Tcmn Communication' => 'Общение',
  'Tcmn Date' => 'Дата',
  'Tcmn Pprs' => 'Менеджер',
  'Tcmn Result' => 'РезУЛЬТАТ',
  'Tcmn Task' => 'Задача',
  'Tcmn Tcst' => 'Статус',
  'Tcmn Tmed' => 'Тип Общение',
  'Tcmn Ttsk' => '',
  'Tcmt' => '',
  'Tcmt Comments' => 'Комментарии',
  'Tcmt Datetime' => 'Дата',
  'Tcmt Notes' => 'Примечания',
  'Tcmt Pprs' => 'Менеджер',
  'Tcmt Ttsk' => '',
  'Tcsh' => '',
  'Tcsh Datetime' => 'Дата',
  'Tcsh Pprs' => '',
  'Tcsh Tcmn' => '',
  'Tcsh Tcst' => '',
  'Tcst' => '',
  'Tcst Icon' => '',
  'Tcst Name' => 'Название',
  'Tmed' => '',
  'Tmed Icon' => '',
  'Tmed Name' => 'Название',
  'Tprs' => '',
  'Tprs Persons' => 'Менеджеры',
  'Tprs Pprs' => 'Менеджеры',
  'Tprs Ttsk' => '',
  'Tsth' => '',
  'Tsth Datetime' => 'Дата',
  'Tsth Pprs' => 'Менеджер',
  'Tsth Tstt' => 'Статус',
  'Tsth Ttsk' => '',
  'Tstt' => '',
  'Tstt Icon' => '',
  'Tstt Name' => 'Название',
  'Ttsk' => '',
  'Ttsk Ccmp' => 'Клиент',
  'Ttsk Description' => 'Описание',
  'Ttsk Name' => 'Название',
  'Ttsk Notes' => 'Примечания',
  'Ttsk Tasks' => '',
  'Ttsk Tstt' => 'Статус',
  'tooltip.ttsk_ccmp_id' => '',
  'tooltip.ttsk_description' => '',
  'tooltip.ttsk_id' => '',
  'tooltip.ttsk_name' => 'Название',
);
