<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Task' => 'Добавить задачу',
  'Client' => 'Клиент',
  'Create New Project' => 'Создать новый проект',
  'Projects' => 'Проекты',
  'Task' => 'Задача',
  'Task Name' => 'Название',
  'Tasks' => 'Задачи',
  'Tcmn' => '',
  'Tcmn Datetime' => 'Время',
  'Tcmn Task' => 'Задача',  
  'Tcmn Ttsk' => '',
  'Tcmt' => '',
  'Tcmt Ttsk' => '',
  'Tcsh' => '',
  'Tcsh Pprs' => '',
  'Tcsh Tcmn' => '',
  'Tcsh Tcst' => '',
  'Tcst' => '',
  'Tcst Icon' => '',
  'Tmed' => '',
  'Tmed Icon' => '',
  'Tprs' => '',
  'Tprs Ttsk' => '',
  'Tsth' => '',
  'Tsth Ttsk' => '',
  'Tstt' => '',
  'Tstt Icon' => '',
  'Ttsk' => '',
  'tooltip.tcmn_client_pprs_id' => '',
  'tooltip.tcmn_datetime' => '',
  'tooltip.tcmn_id' => '',
  'tooltip.tcmn_pprs_id' => '',
  'tooltip.tcmn_task' => '',
  'tooltip.tcmn_tcst_id' => '',
  'tooltip.tcmn_tmed_id' => '',
  'tooltip.ttsk_ccmp_id' => '',
  'tooltip.ttsk_description' => '',
  'tooltip.ttsk_id' => '',
  'Tcmn Date' => '@@Дата@@',
  'Add Comment' => 'Добавить комментарий',
  'Communication Plan Date' => 'Дата',
  'Person' => 'Менеджер',
  'Project' => 'Проект',
  'Project details' => 'Детали проекта',
  'Projects list' => 'Список проектов',
  'Tcmn Client Pprs' => 'Представитель',
  'Tcmn Pprs' => 'Менеджер',
  'Tcmn Result' => 'Результат',
  'Tcmn Tcst' => 'Статус',
  'Tcmn Tmed' => 'Тип Общение',
  'Tcmt Comments' => 'Комментарии',
  'Tcmt Datetime' => 'Дата',
  'Tcmt Notes' => 'Примечания',
  'Tcmt Pprs' => 'Менеджер',
  'Tcsh Datetime' => 'Дата',
  'Tcst Name' => 'Название',
  'Tmed Name' => 'Название',
  'Tprs Persons' => 'Менеджеры',
  'Tprs Pprs' => 'Менеджеры',
  'Tsth Datetime' => 'Дата',
  'Tsth Pprs' => 'Менеджер',
  'Tsth Tstt' => 'Статус',
  'Tstt Name' => 'Название',
  'Ttsk Ccmp' => 'Клиент',
  'Ttsk Description' => 'Описание',
  'Ttsk Name' => 'Название',
  'Ttsk Notes' => 'Примечания',
  'Ttsk Tstt' => 'Статус',
  'tooltip.ttsk_name' => 'Название',
);
