<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Comment' => '',
  'Communication Plan Date' => '',
  'Create New Task' => '',
  'Create Ttsk Task' => '',
  'Person' => '',
  'Task details' => '',
  'Task details: ' => '',
  'Tasks list' => '',
  'Tcmn' => '',
  'Tcmn Client Pprs' => '',
  'Tcmn Communication' => '',
  'Tcmn Date' => '',
  'Tcmn Pprs' => '',
  'Tcmn Result' => '',
  'Tcmn Task' => '',
  'Tcmn Tcst' => '',
  'Tcmn Tmed' => '',
  'Tcmn Ttsk' => '',
  'Tcmt' => '',
  'Tcmt Comments' => '',
  'Tcmt Datetime' => '',
  'Tcmt Notes' => '',
  'Tcmt Pprs' => '',
  'Tcmt Ttsk' => '',
  'Tcsh' => '',
  'Tcsh Datetime' => '',
  'Tcsh Pprs' => '',
  'Tcsh Tcmn' => '',
  'Tcsh Tcst' => '',
  'Tcst' => '',
  'Tcst Icon' => '',
  'Tcst Name' => '',
  'Tmed' => '',
  'Tmed Icon' => '',
  'Tmed Name' => '',
  'Tprs' => '',
  'Tprs Persons' => '',
  'Tprs Pprs' => '',
  'Tprs Ttsk' => '',
  'Tsth' => '',
  'Tsth Datetime' => '',
  'Tsth Pprs' => '',
  'Tsth Tstt' => '',
  'Tsth Ttsk' => '',
  'Tstt' => '',
  'Tstt Icon' => '',
  'Tstt Name' => '',
  'Ttsk' => '',
  'Ttsk Ccmp' => '',
  'Ttsk Description' => '',
  'Ttsk Name' => '',
  'Ttsk Notes' => '',
  'Ttsk Tasks' => '',
  'Ttsk Tstt' => '',
  'tooltip.ttsk_ccmp_id' => '',
  'tooltip.ttsk_description' => '',
  'tooltip.ttsk_id' => '',
  'tooltip.ttsk_name' => '',
);
