<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Comment' => '',
  'Communication Plan Date' => 'Date',
  'Create New Task' => '',
  'Create Ttsk Task' => '',
  'Person' => 'Manager',
  'Task details' => '',
  'Task details: ' => '',
  'Tasks list' => '',
  'Tcmn' => '',
  'Tcmn Client Pprs' => 'Client Person',
  'Tcmn Communication' => 'Communication',
  'Tcmn Date' => 'Date',
  'Tcmn Pprs' => 'Manager',
  'Tcmn Result' => 'Result',
  'Tcmn Task' => 'Task',
  'Tcmn Tcst' => 'Status',
  'Tcmn Tmed' => 'Comm. Type',
  'Tcmn Ttsk' => '',
  'Tcmt' => '',
  'Tcmt Comments' => 'Comments',
  'Tcmt Datetime' => 'Date',
  'Tcmt Notes' => 'Notes',
  'Tcmt Pprs' => 'Manager',
  'Tcmt Ttsk' => '',
  'Tcsh' => '',
  'Tcsh Datetime' => 'Date',
  'Tcsh Pprs' => '',
  'Tcsh Tcmn' => '',
  'Tcsh Tcst' => '',
  'Tcst' => '',
  'Tcst Icon' => '',
  'Tcst Name' => 'Name',
  'Tmed' => '',
  'Tmed Icon' => '',
  'Tmed Name' => '',
  'Tprs' => '',
  'Tprs Persons' => 'Managers',
  'Tprs Pprs' => 'Managers',
  'Tprs Ttsk' => '',
  'Tsth' => '',
  'Tsth Datetime' => 'Date',
  'Tsth Pprs' => 'Manager',
  'Tsth Tstt' => 'Status',
  'Tsth Ttsk' => '',
  'Tstt' => '',
  'Tstt Icon' => '',
  'Tstt Name' => 'Name',
  'Ttsk' => '',
  'Ttsk Ccmp' => 'Client',
  'Ttsk Description' => 'Description',
  'Ttsk Name' => 'Name',
  'Ttsk Notes' => 'Notes',
  'Ttsk Tasks' => 'Tasks',
  'Ttsk Tstt' => 'Status',
  'tooltip.ttsk_ccmp_id' => '',
  'tooltip.ttsk_description' => '',
  'tooltip.ttsk_id' => '',
  'tooltip.ttsk_name' => '',
);
