<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Comment' => '',
  'Add Task' => '',
  'Client' => '',
  'Create New Project' => '',
  'Project details' => '',
  'Projects list' => '',
  'Task' => '',
  'Task Name' => '',
  'Tasks' => '',
  'Tcmn' => '',
  'Tcmn Datetime' => 'Time',
  'Tcmn Task' => 'Task',      
  'Tcmn Ttsk' => '',
  'Tcmt' => '',
  'Tcmt Ttsk' => '',
  'Tcsh' => '',
  'Tcsh Pprs' => '',
  'Tcsh Tcmn' => '',
  'Tcsh Tcst' => '',
  'Tcst' => '',
  'Tcst Icon' => '',
  'Tmed' => '',
  'Tmed Icon' => '',
  'Tmed Name' => '',
  'Tprs' => '',
  'Tprs Ttsk' => '',
  'Tsth' => '',
  'Tsth Ttsk' => '',
  'Tstt' => '',
  'Tstt Icon' => '',
  'Ttsk' => '',
  'tooltip.tcmn_client_pprs_id' => '',
  'tooltip.tcmn_datetime' => '',
  'tooltip.tcmn_id' => '',
  'tooltip.tcmn_pprs_id' => '',
  'tooltip.tcmn_task' => '',
  'tooltip.tcmn_tcst_id' => '',
  'tooltip.tcmn_tmed_id' => '',
  'tooltip.ttsk_ccmp_id' => '',
  'tooltip.ttsk_description' => '',
  'tooltip.ttsk_id' => '',
  'tooltip.ttsk_name' => '',
  'Tcmn Date' => '@@Date@@',
  'Communication Plan Date' => 'Date',
  'Person' => 'Manager',
  'Project' => '',
  'Projects' => '',
  'Tcmn Client Pprs' => 'Client Person',
  'Tcmn Pprs' => 'Manager',
  'Tcmn Result' => 'Result',
  'Tcmn Tcst' => 'Status',
  'Tcmn Tmed' => 'Comm. Type',
  'Tcmt Comments' => 'Comments',
  'Tcmt Datetime' => 'Date',
  'Tcmt Notes' => 'Notes',
  'Tcmt Pprs' => 'Manager',
  'Tcsh Datetime' => 'Time',
  'Tcst Name' => 'Name',
  'Tprs Persons' => 'Managers',
  'Tprs Pprs' => 'Managers',
  'Tsth Datetime' => 'Date',
  'Tsth Pprs' => 'Manager',
  'Tsth Tstt' => 'Status',
  'Tstt Name' => 'Name',
  'Ttsk Ccmp' => 'Client',
  'Ttsk Description' => 'Description',
  'Ttsk Name' => 'Name',
  'Ttsk Notes' => 'Notes',
  'Ttsk Tstt' => 'Status',
);
