<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Task' => 'Uzdevums',
  'Task Name' => '',
  'Tasks' => 'Uzdevumi',
  'Tcmn' => '',
  'Tcmn Datetime' => 'Laiks',
  'Tcmn Task' => 'Uzdevums',  
  'Tcmn Ttsk' => '',
  'Tcmt' => '',
  'Tcmt Ttsk' => '',
  'Tcsh' => '',
  'Tcsh Tcmn' => '',
  'Tcsh Tcst' => '',
  'Tcst' => '',
  'Tcst Icon' => '',
  'Tmed Icon' => '',
  'Tprs' => '',
  'Tprs Ttsk' => '',
  'Tsth' => '',
  'Tsth Ttsk' => '',
  'Tstt' => '',
  'Tstt Icon' => '',
  'Ttsk' => '',
  'tooltip.tcmn_client_pprs_id' => '',
  'tooltip.tcmn_datetime' => '',
  'tooltip.tcmn_id' => '',
  'tooltip.tcmn_pprs_id' => '',
  'tooltip.tcmn_task' => '',
  'tooltip.tcmn_tcst_id' => '',
  'tooltip.tcmn_tmed_id' => '',
  'tooltip.ttsk_ccmp_id' => '',
  'tooltip.ttsk_description' => '',
  'tooltip.ttsk_id' => '',
  'tooltip.ttsk_name' => '',
  'Add Comment' => 'Pievienot Komentārus',
  'Add Task' => 'Pievienot uzdevumu',
  'Client' => 'Klients',
  'Communication Plan Date' => 'Datums',
  'Create New Project' => 'Izveidot jaunu uzdevumu',
  'Person' => 'Menedžeris',
  'Project' => 'Projekts',
  'Project details' => 'Projekta detaļas',
  'Projects' => 'Projekti',
  'Projects list' => 'Projektu saraksts',
  'Tcmn Client Pprs' => 'Klienta Pārstāvis',
  'Tcmn Pprs' => 'Menedžeris',
  'Tcmn Result' => 'Rezultāts',
  'Tcmn Tcst' => 'Statuss',
  'Tcmn Tmed' => 'Mēdijs',
  'Tcmt Comments' => 'Komentāri',
  'Tcmt Datetime' => 'Laiks',
  'Tcmt Notes' => 'Komentāri',
  'Tcmt Pprs' => 'Konultants',
  'Tcsh Datetime' => 'Datums',
  'Tcsh Pprs' => 'Menedžeris',
  'Tcst Name' => 'Nosaukums',
  'Tmed' => 'Mēdijs',
  'Tmed Name' => 'Nosaukums',
  'Tprs Persons' => 'Menedžeri',
  'Tprs Pprs' => 'Menedžeris',
  'Tsth Datetime' => 'Laiks',
  'Tsth Pprs' => 'Menedžeris',
  'Tsth Tstt' => 'Statuss',
  'Tstt Name' => 'Nosaukums',
  'Ttsk Ccmp' => 'Uzņēmums',
  'Ttsk Description' => 'Apraksts',
  'Ttsk Name' => 'Nosaukums',
  'Ttsk Notes' => 'Piezīmes',
  'Ttsk Tstt' => 'Statuss',
);
